### ISSUE TITLE
TP2bis :)

### ISSUE THREAD

**Issue by BertrandD** [Nils-Laurent/TP-Analyse#2]
Je suis dessus !

**Comment by Nils-Laurent** [comment]
Attends, jette un oeuil dans le rapport je déjà fait quelques trucs

**Comment by BertrandD** [comment]
déjà finis XD Je merge tout ça de toute façon :)

**Comment by BertrandD** [comment]
C'est good pour toi @Nils-Laurent ? Si c'est bon j'imprime ! La prochaine fois on évitera de faire la même chose en même temps ^^
